name: Run Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.4
          check-latest: true

      - name: Run tests
        run: go test -v ./...